name: 'event_stream_demo'

config-version: 2

profile: 'event_stream_demo'

model-paths: ['models']
analysis-paths: ['analysis']
test-paths: ['tests']
target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'


models:
  event_stream_demo:
    +materialized: table
    00_utilities:
      +schema: utilities
    01_staging:
      +schema: staging
    02_int:
      +schema: int
      +materialized: "{{ 'table' if target.name == 'dev' else 'ephemeral' }}" # materialize as table in dev to catch errors where they appear; and ephemeral in production for efficiency
    03_analytics:
      +schema: analytics


seed-paths: ['seeds']
seeds:
  event_stream_demo:
    +schema: raw