version: 2

models:
  - name: dim_users
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
      - name: country_code
        tests:
          - not_null
      - name: country
        tests:
          - not_null
      - name: region
        tests:
          - not_null
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null

  - name: dim_posts
    columns:
      - name: post_id
        tests:
          - not_null
          - unique
      - name: author_user_id
        tests:
          - not_null
          # fk relationship test would fail because soft-deleted rows are removed
      - name: author_country_code
        tests:
          - not_null
      - name: author_country
        tests:
          - not_null
      - name: author_region
        tests:
          - not_null
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null

  - name: fct_events
    columns:
      - name: event_id
        tests:
          - not_null
          - unique
      - name: user_id
        tests:
          - not_null
          # fk relationship test would fail because soft-deleted rows are removed
      - name: post_id
        tests:
          - not_null
          # fk relationship test would fail because soft-deleted rows are removed
      - name: created_at
        tests:
          - not_null
      - name: event_type
        tests:
          - not_null
          - accepted_values:
              values: ['like', 'view']
      - name: is_like
        tests:
          - not_null
      - name: partition_date
        tests:
          - not_null
