version: 2

models:
  - name: dim_users
    columns:
      - name: user_id
        data_tests:
          - not_null
          - unique
      - name: country_code
        data_tests:
          - not_null
      - name: country
        data_tests:
          - not_null
      - name: region
        data_tests:
          - not_null
      - name: created_at
        data_tests:
          - not_null
      - name: updated_at
        data_tests:
          - not_null

  - name: dim_posts
    columns:
      - name: post_id
        data_tests:
          - not_null
          - unique
      - name: creator_id
        data_tests:
          - not_null
          # fk relationship test would fail because soft-deleted rows are removed
      - name: creator_country_code
        data_tests:
          - not_null
      - name: creator_country
        data_tests:
          - not_null
      - name: creator_region
        data_tests:
          - not_null
      - name: created_at
        data_tests:
          - not_null
      - name: updated_at
        data_tests:
          - not_null

  - name: fct_events
    columns:
      - name: event_id
        data_tests:
          - not_null
          - unique
      - name: user_id
        data_tests:
          - not_null
          # fk relationship test would fail because soft-deleted rows are removed
      - name: post_id
        data_tests:
          - not_null
          # fk relationship test would fail because soft-deleted rows are removed
      - name: created_at
        data_tests:
          - not_null
      - name: event_type
        data_tests:
          - not_null
          - accepted_values:
              values: ['like', 'view']
      - name: is_like
        data_tests:
          - not_null
      - name: partition_date
        data_tests:
          - not_null
