version: 2

sources:
  - name: raw
    description: Raw data ingested from mock data generation script
    schema: raw
    tables:
      - name: user
        columns:
          - name: user_id
            description: Primary key for users
            data_tests:
              - unique
              - not_null
          - name: first_name
            data_tests:
              - not_null
          - name: last_name
            data_tests:
              - not_null
          - name: created_at
            data_tests:
              - not_null
          - name: country_code
            data_tests:
              - not_null

      - name: post
        columns:
          - name: post_id
            description: Primary key for posts
            data_tests:
              - unique
              - not_null
          - name: user_id
            description: Foreign key to users table
            data_tests:
              - not_null
              - relationships:
                  to: source('raw', 'user')
                  field: user_id
          - name: post_text
            data_tests:
              - not_null
          - name: created_at
            data_tests:
              - not_null

      - name: event
        columns:
          - name: event_id
            description: Primary key for events
            data_tests:
              - unique
              - not_null
          - name: user_id
            description: Foreign key to users table
            data_tests:
              - not_null
              - relationships:
                  to: source('raw', 'user')
                  field: user_id
          - name: post_id
            description: Foreign key to posts table
            data_tests:
              - not_null
              - relationships:
                  to: source('raw', 'post')
                  field: post_id
          - name: created_at
            data_tests:
              - not_null
          - name: event_type
            data_tests:
              - not_null
              - accepted_values:
                  values: ['view', 'like']
